<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site1.Master" CodeBehind="WebForm1.aspx.vb" Inherits="WebApplication5.WebForm1" UnobtrusiveValidationMode="None" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" type="text/css" href="Styles/StyleSheetGeneral.css" />
    <link rel="stylesheet" type="text/css" href="Styles/style_Large.css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="Main-Content">
        <div class="first-panel">
            <br />
            <span style="left: 150px;">
                <asp:GridView ID="gridViewTickets" runat="server"
                    AutoGenerateColumns="False"
                    AutoGenerateSelectButton="True"
                    AlternatingRowStyle-BackColor="Wheat"
                    AlternatingRowStyle-Font-Bold="true"
                    BackColor="White"
                    Caption="Tickets"
                    CaptionAlign="Left"
                    AlternatingRowStyle-BorderColor="WindowText"
                    AlternatingRowStyle-Font-Italic="false"
                    AlternatingRowStyle-Font-Underline="true"
                    AllowSorting="True"
                    AllowPaging="True"
                    AutoGenerateDeleteButton="True"
                    OnRowDeleting="gridViewTickets_RowDeleting"
                    AutoGenerateEditButton="False"
                    OnRowEditing="gridViewTickets_RowEditing"
                    ShowFooter="true"
                    OnRowCancelingEdit="gridViewTickets_RowCancelingEdit"
                    OnRowUpdating="gridViewTickets_RowUpdating"
                    PageSize="11"
                    OnPageIndexChanging="gridViewTickets_PageIndexChanging"
                    GridLines="None"
                    DataKeyNames="TicketNumber"
                    SelectedRowStyle-BackColor="#ffcc00"
                    OnSorting="gridViewTickets_Sorting">
                    
                    <PagerStyle BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px" HorizontalAlign="Center" VerticalAlign="Middle" />
                    <AlternatingRowStyle BackColor="Wheat" BorderColor="WindowText" Font-Bold="True" Font-Italic="False" Font-Underline="True"></AlternatingRowStyle>
                    <Columns>
                        <asp:BoundField DataField="ticketNumber" HeaderText="Ticket Number"
                            ItemStyle-Width="100px" ItemStyle-HorizontalAlign="Center" SortExpression="ticketNumber">
                        </asp:BoundField>
                        <asp:BoundField DataField="licensePlate" HeaderText="License Plate"
                            ItemStyle-Width="100px" ItemStyle-HorizontalAlign="Center">
                        </asp:BoundField>
                        <asp:BoundField DataField="licenseState" HeaderText="License State"
                            ItemStyle-Width="100px" ItemStyle-HorizontalAlign="Center">
                        </asp:BoundField>
                        <asp:BoundField DataField="ticketDate" HeaderText="Ticket Date"
                            ItemStyle-Width="100px" ItemStyle-HorizontalAlign="Center">
                        </asp:BoundField>
                        <asp:TemplateField HeaderText="Violation Type">
                            <EditItemTemplate>
                                <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("ViolationType") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("ViolationType") %>'></asp:Label>
                            </ItemTemplate>
                            <ItemStyle HorizontalAlign="Center" Width="100px" />
                        </asp:TemplateField>
                        <asp:TemplateField>
                            <ItemTemplate>
                                <asp:Label ID="Label7" runat="server" Text='<%# Eval("vehicleType")%>' />
                                <asp:Label ID="Label3" runat="server" Text=" / " />
                                <asp:Label ID="Label4" runat="server" Text='<%# Eval("vehicleMake")%>' />
                                <br />
                                <asp:Label ID="Label11" runat="server" Text='<%# Eval("blockNumber")%>' />
                                <asp:Label ID="Label12" runat="server" Text=" " />
                                <asp:Label ID="Label9" runat="server" Text='<%# Eval("street")%>' />
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>

                    <SelectedRowStyle BackColor="#FFCC00"></SelectedRowStyle>
                </asp:GridView>
            </span>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:mySQLConnection %>"
                DeleteCommand="DELETE FROM [Tickets] WHERE [TicketNumber] = @TicketNumber"
                InsertCommand="INSERT INTO [Tickets] ([TicketNumber], [VehicleType]) VALUES (@TicketNumber, @VehicleType)"
                SelectCommand="SELECT [TicketNumber], [VehicleType] FROM [Tickets]"
                UpdateCommand="UPDATE [Tickets] SET [VehicleType] = @VehicleType WHERE [TicketNumber] = @TicketNumber">
                <DeleteParameters>
                    <asp:Parameter Name="TicketNumber" Type="String" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="TicketNumber" Type="String" />
                    <asp:Parameter Name="VehicleType" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="VehicleType" Type="String" />
                    <asp:Parameter Name="TicketNumber" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <asp:Label ID="SelectedRow" runat="server"></asp:Label>
            <span style="left: 150px;">
                <asp:GridView ID="GridViewTicketsSQL" runat="server" BackColor="#DEBA84"
                    BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px"
                    CellPadding="3" CellSpacing="2"
                    AutoGenerateColumns="False"
                    DataKeyNames="TicketNumber"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateEditButton="true"
                    AutoGenerateDeleteButton="true"
                    ShowFooter="True">

                    <Columns>
                        <asp:TemplateField HeaderText="TicketNumber" SortExpression="TicketNumber"
                            HeaderStyle-Width="60px" ItemStyle-Width="100px" ItemStyle-HorizontalAlign="Center">
                            <EditItemTemplate>
                                <asp:Label ID="Label1" runat="server" Text='<%# Eval("TicketNumber") %>'></asp:Label>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("TicketNumber") %>'></asp:Label>
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="ticketNumber" runat="server"></asp:TextBox>
                                <asp:RequiredFieldValidator runat="server" ErrorMessage="Ticket Number Needed"
                                    ControlToValidate="ticketNumber" Text="*"
                                    ValidationGroup="Insert" ForeColor="Red"></asp:RequiredFieldValidator>
                                <asp:LinkButton ValidationGroup="Insert" ID="LinkButton1" runat="server" OnClick="LinkButton1_Click">Insert</asp:LinkButton>
                            </FooterTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="VehicleType" SortExpression="VehicleType"
                            HeaderStyle-Width="60px" ItemStyle-Width="100px" ItemStyle-HorizontalAlign="Center">
                            <EditItemTemplate>
                                <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("VehicleType") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="vehicleType1" runat="server" ErrorMessage="Vehicle Type Needed update"
                                    ControlToValidate="TextBox1" Text="*" ForeColor="Red"></asp:RequiredFieldValidator>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("VehicleType") %>'></asp:Label>
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="vehicleType" runat="server"></asp:TextBox>
                                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server"
                                    ErrorMessage="Vehicle Type Needed" ControlToValidate="vehicleType" Text="*"
                                    ValidationGroup="Insert" ForeColor="Red"></asp:RequiredFieldValidator>
                            </FooterTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
                    <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
                    <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
                    <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
                    <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#FFF1D4" />
                    <SortedAscendingHeaderStyle BackColor="#B95C30" />
                    <SortedDescendingCellStyle BackColor="#F1E5CE" />
                    <SortedDescendingHeaderStyle BackColor="#93451F" />
                </asp:GridView>
                <asp:ValidationSummary ID="ValidationSummary1" ValidationGroup="Insert" ForeColor="Red" runat="server" />
                <asp:ValidationSummary ID="ValidationSummary2" ForeColor="Red" runat="server" />
            </span>
            <h1>New skills. Improved skills. Now.</h1>
            <h3>Learn technology, creative and business skills you can use today.</h3>
            <div class="cards">
                <div style="height: 25%; width: 100%; overflow: hidden;">
                    <div style="float: left; width: 200px; height: 250px; text-align: center; vertical-align: central;">
                        <button class="button" style="background-color: #706d3c; text-align: center; /*opacity: 0.9; */">
                            Developer<br />
                            <br />
                            <img src="Images/deve.PNG" /></button>
                    </div>
                    <div style="float: left; width: 200px; height: 250px; text-align: center; vertical-align: central;">
                        <button class="button" style="background-color: #e65527; text-align: center; /*opacity: 0.9; */">
                            Design<br />
                            <br />
                            <img src="Images/design.PNG" /></button>
                    </div>
                    <div style="float: left; width: 200px; height: 250px; text-align: center; vertical-align: central;">
                        <button class="button" style="background-color: teal; text-align: center; /*opacity: 0.9; */">
                            Web<br />
                            <br />
                            <img src="Images/web.PNG" /></button>
                    </div>
                    <div style="float: left; width: 200px; height: 250px; text-align: center; vertical-align: central;">
                        <button class="button" style="background-color: #363948; text-align: center; /*opacity: 0.9; */">
                            Photography<br />
                            <br />
                            <img src="Images/photography.PNG" /></button>
                    </div>
                    <div style="float: left; width: 200px; height: 250px; text-align: center; vertical-align: central;">
                        <button class="button" style="background-color: #716f84; text-align: center; /*opacity: 0.9; */">
                            Business<br />
                            <br />
                            <img src="Images/business.PNG" /></button>
                    </div>
                </div>
                <div style="height: 25%; width: 100%; overflow: hidden;">
                    <div style="float: left; width: 200px; height: 250px; text-align: center; vertical-align: central;">
                        <button class="button" style="background-color: #d5bc3a; text-align: center; /*opacity: 0.9; */">
                            Education<br />
                            <br />
                            <img src="Images/education.PNG" /></button>
                    </div>
                    <div style="float: left; width: 200px; height: 250px; text-align: center; vertical-align: central;">
                        <button class="button" style="background-color: #5ea07f; font-size: 20px; text-align: center; /*opacity: 0.9; */">
                            3D+Animation<br />
                            <br />
                            <img src="Images/3dAnimation.PNG" /></button>
                    </div>
                    <div style="float: left; width: 200px; height: 250px; text-align: center; vertical-align: central;">
                        <button class="button" style="background-color: #1d6285; text-align: center; /*opacity: 0.9; */">
                            Video<br />
                            <br />
                            <img src="Images/video.PNG" /></button>
                    </div>
                    <div style="float: left; width: 200px; height: 250px; text-align: center; vertical-align: central;">
                        <button class="button" style="background-color: #86b3bb; text-align: center; /*opacity: 0.9; */">
                            Audio<br />
                            <br />
                            <img src="Images/audio.PNG" /></button>
                    </div>
                    <div style="float: left; width: 200px; height: 250px; background-color: #000; text-align: center; vertical-align: central; padding-top: 30px;">
                        <label class="label" style="font-size: 25px;">
                            Become a
                            <br />
                            Member</label><br />
                        <button style="background-color: #f1af05; color: black; font-family: Helvetica, Arial,sans-serif; height: 40px; width: 120px; border: none; font-size: 20px; text-align: center;">Try it Free</button>
                    </div>
                </div>
            </div>
            <br />
            <div style="margin-left: 250px;">
                <a href="#" style="text-decoration: none; font-size: small; color: #61532e;"><b>More Information</b></a>
            </div>

        </div>
        <div class="second-panel" style="font-family: Helvetica, Arial,sans-serif; padding: 10px;">
            <div class="second-panel" style="font-family: Helvetica, Arial,sans-serif;">
                <div>
                    <h2>All memberships include</h2>
                    <div style="height: 20%; width: 100%; overflow: hidden;">
                        <div style="float: left; width: 320px; height: 150px;">
                            <div style="height: 95px; width: 320px; overflow: hidden; padding: 15px;">
                                <div style="float: left; width: 32px; height: 34px;">
                                    <img src="Images/lock.PNG" />
                                </div>
                                <div style="float: left; width: 240px; height: 90px; padding-left: 2px; padding-top: 5px;">
                                    <label>
                                        <b>Unlimited Access</b><br />
                                        <br />
                                        <span style="font-size: smaller;">
                                            <b>Learn what you want</b>, when you want,
                                            <br />
                                            from our entire course library.</span>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div style="float: left; width: 320px; height: 150px; text-align: left;">
                            <div style="height: 95px; width: 320px; overflow: hidden; padding: 15px;">
                                <div style="float: left; width: 32px; height: 34px;">
                                    <img src="Images/play1.PNG" />
                                </div>
                                <div style="float: left; width: 240px; height: 90px; padding-left: 2px; padding-top: 5px;">
                                    <label>
                                        <span style="font-size: smaller;">
                                            <b>4,290 video courses</b><br />
                                            <br />
                                            <b>Find what you need</b> in our growing library.
                                    New courses added weekly.</span>
                                    </label>
                                </div>
                            </div>

                        </div>
                        <div style="float: left; width: 320px; height: 150px; text-align: left; vertical-align: central;">
                            <div style="height: 95px; width: 320px; overflow: hidden; padding: 15px;">
                                <div style="float: left; width: 32px; height: 34px;">
                                    <img src="Images/teachers.PNG" />
                                </div>
                                <div style="float: left; width: 240px; height: 90px; padding-left: 2px; padding-top: 5px;">
                                    <label>
                                        <b>Expert teachers</b><br />
                                        <br />
                                        <span style="font-size: smaller;">Watch and learn from <b>top experts</b> who<br />
                                            are passionate about teaching.</span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div style="height: 20%; width: 100%; overflow: hidden;">
                        <div style="float: left; width: 320px; height: 150px; text-align: left; vertical-align: central;">
                            <div style="height: 95px; width: 320px; overflow: hidden; padding: 15px;">
                                <div style="float: left; width: 32px; height: 34px;">
                                    <img src="Images/build.PNG" />
                                </div>
                                <div style="float: left; width: 240px; height: 90px; padding-left: 2px; padding-top: 5px;">
                                    <label>
                                        <b>Variety of instruction</b><br />
                                        <br />
                                        <span style="font-size: smaller;"><b>Courses for all levels</b> cover technical
                                    <br />
                                            skills, creative techniques, business<br />
                                            strategies, and more.</span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div style="float: left; width: 320px; height: 150px; text-align: left; vertical-align: central;">
                            <div style="height: 95px; width: 320px; overflow: hidden; padding: 15px;">
                                <div style="float: left; width: 32px; height: 34px;">
                                    <img src="Images/mobile.PNG" />
                                </div>
                                <div style="float: left; width: 240px; height: 90px; padding-left: 2px; padding-top: 5px;">
                                    <label>
                                        <b>On-the-go learning</b><br />
                                        <br />
                                        <span style="font-size: smaller;">Watch from your <b>computer, tablet, or<br />
                                            mobile device</b>. Switch back and
                                            <br />
                                            forth as you choose.</span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div style="float: left; width: 320px; height: 150px; text-align: left; vertical-align: central;">
                            <div style="height: 95px; width: 320px; overflow: hidden; padding: 15px;">
                                <div style="float: left; width: 32px; height: 34px;">
                                    <img src="Images/play2.PNG" />
                                </div>
                                <div style="float: left; width: 240px; height: 90px; padding-left: 2px; padding-top: 5px;">
                                    <label>
                                        <b>Custom playlists</b><br />
                                        <br />
                                        <span style="font-size: smaller;"><b>Create and save lists of courses</b> you<br />
                                            want to watch, and share them with<br />
                                            friends or colleagues.
                                        </span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr />
            </div>
        </div>

        <div class="third-panel">
            <table>
                <tr>
                    <td>
                        <h2>Watch. Listen. Practice. Learn.</h2>
                        <p style="font-size: 15px; line-height: 25px;">
                            <b>You set the pace</b> with online learning.<br />
                            Learn what you want, when you want, and practice with the instructor's files while you watch and listen.
                        </p>
                        <div style="height: 75px; width: 400px; overflow: hidden; background-color: #d6d4d0; border-radius: 10px; padding: 15px;">
                            <div style="float: left; width: 65px; height: 40px;">
                                <img src="Images/tweet.PNG" />
                            </div>
                            <div style="float: left; width: 330px; height: 70px; padding-top: 5px; padding-left: 2px;">
                                <label style="font-size: 15px; line-height: 25px;">
                                    @lynda Just discovered you today - Thank
                                    <br />
                                    You! For making learning easy & enjoyable!<br />
                                    <span style="color: dodgerblue;">@dawnmcfresh</span>
                                </label>
                            </div>
                        </div>
                    </td>
                    <td>
                        <img src="Images\laptop-bg.jpg" alt="My laptop" /></td>
                </tr>
            </table>
            <hr />
        </div>

        <div class="fourth-panel">
            <table>
                <tr>
                    <td>
                        <div class="fourth-panel-cards">
                            <div style="height: 100%; width: 100%; overflow: hidden;">
                                <div style="float: left; width: 110px; height: 90px; text-align: center; vertical-align: central;">
                                    <button>
                                        <img src="Images/Design4.PNG" />
                                        <p>Design</p>
                                    </button>
                                </div>
                                <div style="float: left; width: 110px; height: 90px; text-align: center; vertical-align: central;">
                                    <button>
                                        <img src="Images/Developer4.PNG" />
                                        <p>Developer</p>
                                    </button>
                                </div>
                                <div style="float: left; width: 110px; height: 90px; text-align: center; vertical-align: central;">
                                    <button>
                                        <img src="Images/Web4.PNG" />
                                        <p>Web</p>
                                    </button>
                                </div>
                                <div style="float: left; width: 110px; height: 90px; text-align: center; vertical-align: central;">
                                    <button>
                                        <img src="Images/Business4.PNG" />
                                        <p>Business</p>
                                    </button>
                                </div>
                            </div>
                            <hr style="visibility: hidden" />
                            <div style="height: 100%; width: 100%; overflow: hidden;">
                                <div style="float: left; width: 110px; height: 90px; text-align: center; vertical-align: central;">
                                    <button>
                                        <img src="Images/Photo4.PNG" />
                                        <p>
                                            Photography<p />
                                    </button>
                                </div>
                                <div style="float: left; width: 110px; height: 90px; text-align: center; vertical-align: central;">
                                    <button>
                                        <img src="Images/Video4.PNG" />
                                        <p>Video</p>
                                    </button>
                                </div>
                                <div style="float: left; width: 110px; height: 90px; text-align: center; vertical-align: central;">
                                    <button>
                                        <img src="Images/Audio4.PNG" />
                                        <p>Audio</p>
                                    </button>
                                </div>
                                <div style="float: left; width: 110px; height: 90px; text-align: center; vertical-align: central;">
                                    <button>
                                        <img src="Images/3d4.PNG" />
                                        <p>3D</p>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td style="width: 100px;"></td>
                    <td>
                        <ul>
                            <li>
                                <h2>Learn digital illustration from a pro.</h2>
                            </li>
                            <li>
                                <p style="font-size: 15px; line-height: 25px;">
                                    Our teachers are effective, passionate educators, who are<br />
                                    also respected authorities in software, creative, and
                        <br />
                                    business fields. They're here to share their expertise in
                        <br />
                                    dozens of topics with you, with courses organized into
                        <br />
                                    these eight subject areas
                                </p>
                            </li>
                        </ul>
                    </td>
                </tr>
            </table>
            <hr />
        </div>
        <div class="fifth-panel">
            <h2 style="text-align: center">A trusted source for knowledge.</h2>
            <table style="width: 923px; margin-left: 74px">
                <tr>
                    <td>
                        <img src="Images/4Million.PNG" alt="4Million+ People" />
                    </td>
                    <td>
                        <p style="font-size: 15px; line-height: 25px;">
                            <b>We provide training to more than 4 million people</b>, and  <span style="color: #0077b5;">our members tell us </span>that lynda.com<br />
                            helps them stay ahead of software updates, pick up brand-new skills,<br />
                            switch careers, land promotions, and explore  new hobbies. What can we help you do?
                        </p>
                    </td>
                </tr>
            </table>
            <div style="height: 26%; width: 110%; overflow: hidden;">
                <div style="float: left; width: 310px; height: 152px; margin-left: 30px;">
                    <div class="tweetsFirst">
                        <div style="float: left; padding-left: 10px;">
                            <img src="Images/PC.PNG" />
                        </div>
                        <div style="float: left; padding-left: 11px;">
                            <label style="font-size: 15px; line-height: 25px;">
                                lynda.com excels at helping<br />
                                busy professionals keep their<br />
                                software skills razor sharp.<br />
                                <span style="color: #0077b5;">—Jill Duffy, PCMag.com</span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="tweets" style="float: left; width: 350px; height: 145px;">
                    <ul>
                        <li>I really love your site. I have learned so<br />
                            much and, thanks to you, I have just<br />
                            released my first app for iPhone.<br />
                            —Stephanie J.
                        </li>
                    </ul>
                </div>
                <div class="tweets" style="float: left; width: 350px; height: 140px;">
                    <ul>
                        <li>Despite knowing about @lynda for<br />
                            years, this week I jumped on board and
                                            <br />
                            I don’t know how I lived without them.<br />
                            #FF
                                            <br />
                            —Justin D.
                        </li>
                    </ul>
                </div>
            </div>
            <a style="float: right;" href="#">Read more from our members>></a><br />
            <br />
            <hr />
        </div>
        <div class="sixth-panel">
            <table>
                <tr>
                    <td>
                        <h2>Training solutions for business,<br />
                            schools, government, and more</h2>

                        <p style="font-size: 15px; line-height: 25px;">
                            In addition to <span style="color: #0077b5;">individual plans, we also offer</span><br />
                            cost-effective  <span style="color: #0077b5;">group memberships</span> that make<br />
                            top-quality video training available to everyone in<br />
                            your organization. <span style="color: #0077b5;">Learn more »</span>
                        </p>
                    </td>
                    <td style="width: 100px;"></td>
                    <td>
                        <img src="Images/trianing.PNG" /></td>
                </tr>
            </table>
            <hr />
        </div>
        <div class="seven-panel">
            <table>
                <tr>
                    <td>
                        <img src="Images/devices.PNG" alt="Devices" /></td>
                    <td style="width: 100px;"></td>
                    <td>
                        <h2>Desktop, mobile, and tablet access</h2>
                        <ul>
                            <li style="font-size: 15px; line-height: 25px;">Mobile site and free apps for iPhone, iPad, and Android devices</li>
                            <li style="font-size: 15px; line-height: 25px;">Switch devices without ever losing your place</li>
                            <li style="font-size: 15px; line-height: 25px;">Offline viewing option for Annual Premium</li>
                        </ul>

                        <table>
                            <tr>
                                <td>
                                    <button style="width: 164px; height: 50px; border: none;">
                                        <img src="Images/Apple.PNG" /></button></td>
                                <td>
                                    <button style="width: 164px; height: 50px; border: none;">
                                        <img src="Images/amazon.PNG" /></button></td>
                            </tr>
                            <tr>
                                <td>
                                    <button style="width: 164px; height: 50px; border: none;">
                                        <img src="Images/windows.PNG" /></button></td>
                                <td>
                                    <button style="width: 164px; height: 50px; border: none;">
                                        <img src="Images/play.PNG" /></button></td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
            <hr />
            <h2 style="text-align: center;">Ready to learn?</h2>
            <button class="button" value="Try it free">Try it Free</button>
            <hr />
        </div>
    </div>
</asp:Content>
